unit constant;
{$N+}
{$G+}
interface
const    {produktions Zeiten}
           soldaten = 400;{50 Soldaten}
           nlevel = 400;
           jager = 200;
           advjager = 250;
           transporter = 260;
           forts = 300;
           Bomber = 320;


            max = 255;   {anzahlder Schiffe insgesamt }
            smartk= 130;{st„rke der Waffen}
            rakk =  140;
            ammok= 20;
            seite = 4000;{gr”áe der Karte immer in tausender schritten}
            pge = 5; {Geschwindigkeit mit der auf Planeten gek„mpft wird
                      je kleiner desto schneller}
            mut =2; {bei welcher šbermacht sich die Schiffe zurckziehen
                       hier 200%}


implementation

end.